### PR TITLE
fixed some clippy warnings

### PR DESCRIPTION
**Pull request by atk**

### CODE REVIEW

**Review by Razican — APPROVED** [review]
Wow! Looks great, thanks! I think we will be using clippy more often after seing how many details we could improve. It would be great to have it in stable. As soon as checks pass, I'll merge.

**Comment by Razican** [comment]
Just a small thing: I changed the base branch to the `develop` branch as specified by the contribution guidelines. Could you rebase and check that the lints are OK with the code in develop? (We have changed many things since the last release) thanks!

**Comment by atk** [comment]
I'll look into it.

**Comment by Razican** [comment]
Closed with https://github.com/SUPERAndroidAnalyzer/super/commit/e11089e70ba7cf78104cf6ddfd2dc067834e17bc.

**Pull request closed without merging**
