### PR TITLE
Added include and exclude rule regexp

### PR DESCRIPTION
**Pull request by gnieto**
Added an inclusion and exclusion regex for each rule.

This should solve https://github.com/SUPERAndroidAnalyzer/super/issues/34

Please, check the rules.json file carefully, as I'm not sure which regex has to be applied for each kind of file.

### CODE REVIEW

**Comment by Chuky9** [comment]
Hello @gnieto!

I have check your modifications and I noticed that you set the ".xml" file to some regex which belongs to ".java" files. At this moment, rules.json only contains "regex" to be applied to .java files and others that must be applied to all files:  IP disclosure, URL disclosure, Hardcoded file separator, email disclosure, Certificate or Keystore disclosure, Passwords(not commited yet).

Once those regex are corrected and all the tests pass I will merge that !

Thank you very much for your collaboration!!

**Comment by gnieto** [comment]
@Chuky9 Changed on https://github.com/SUPERAndroidAnalyzer/super/pull/100/commits/422e125049dcba0ae34729dc489e2db17bde487e

**Comment by gnieto** [comment]
It seems that build is failing on OSX/night because of 'OUT_DIR' not set on env. It does not seem related to the changes I did. Do you know what this error could be related to?

**Review by Razican — APPROVED** [review]
Code seems good, and I like you added the tests. The failures in nightly have been [reported](https://github.com/rust-lang/cargo/issues/3368) in upstream cargo, they are not related to this PR.

**Comment by Chuky9** [comment]
It seems an issue of cargo nightly. Already reported! I merge this then!

Thanks @gnieto for your work!!

**Pull request merged**
