### PR TITLE
Implement tap completion script generation

### PR DESCRIPTION
**Pull request by panicbit**

### CODE REVIEW

**Comment by panicbit** [comment]
This does not include packaging of the completion scripts.

**Review by Razican — COMMENTED** [review]
Seems good, I'm not sure about the `generate_cli()` function though. Seems that if the only thing required is a `.get_matches()` call we can add that to the `main.rs` file, right? and return an `App` from the `generate_cli()` function. That way we don't need the two functions.

About packaging, I have to check how the scripts are generated. Then we only need to add those files to the packages. But I still need to search where are those files stored in different distributions.

**Comment by panicbit** [comment]
I'll change the generate_cli stuff then.

**Comment by Razican** [comment]
So, for packaging: `cargo-deb` uses the `Cargo.toml` file, where you can specify any file that will exist after calling `cargo build --release` and where they will be stored in the system path.

I've been researching with @Br1oP and seems that for Bash in Debian/RedHat based distributions, scripts go in `/usr/share/bash-completion/completions/`.

For ZSH they go in `/usr/share/zsh/site-functions/`, and for FISH they go in `/usr/share/fish/vendor_completions.d`. For the `cargo-deb` implementation it's straightforward, for the RPM is not so easy, but I can explain it briefly:

The spec file is in `rpmbuild/super.spec`. In the `%install` section you will need to first create the directories:

```
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions
mkdir -p %{buildroot}%{_datadir}/fish/vendor_completions.d
mkdir -p %{buildroot}%{_datadir}/zsh/site-functions (only once we have ZSH working)
```

And then install the actual files, but I don't get them generated in my setup with your branch :/

**Comment by Br1oP** [comment]
For ZSH, it might be different depending on the distro. For example, in Debian Jessie I think it is `/usr/share/zsh/vendor-completions/`. We should look into it in more detail.

**Comment by Razican** [comment]
OK, now I understand where the files are generated, in `target/debug/build/super-{hash}/out/`. Which is not really useful, since it will change in each build. But it can be changed. Instead of using `env!("OUT_DIR")`, we should use `env!("CARGO_TARGET_DIR")`. [More info](http://doc.crates.io/environment-variables.html). They will be generated in `target/release`.

**Comment by panicbit** [comment]
@Razican Turns out that `CARGO_TARGET_DIR` is a variable that you can pass _to_ cargo. For buildscripts there is only really `OUT_DIR`, so I did `OUT_DIR/../../`. The scripts will now be generated in `target/release/build/`.
See http://doc.crates.io/environment-variables.html#environment-variables-cargo-sets-for-build-scripts

**Comment by Razican** [comment]
@panicbit could that have any issue in platforms other than Unix? Maybe it would be better to create a `PathBuf` and pop the last two components?

**Comment by panicbit** [comment]
It's probably not an issue, but I agree, we should use Path.

**Comment by panicbit** [comment]
Done :smiley:

**Review by Razican — APPROVED** [review]

**Review by Razican — CHANGES_REQUESTED** [review]
I just noticed that the base branch was `master` instead of `develop`. Seems that there is some conflict with the develop branch, could you fix it? Thanks!

**Comment by panicbit** [comment]
Yeah, I'll take a look as soon as I'm off the train :)

**Comment by panicbit** [comment]
Done :)

**Review by Razican — APPROVED** [review]

**Pull request merged**
